#!/usr/bin/env bash
# This prints "Best School" 10 times but prints "Hi" after the night one

counter_loop=0
while [ $counter_loop -lt 10 ]; do
	if [ $counter_loop -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter_loop++))
done

