#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8


cp /etc/hosts ~/hosts_tmp
echo "127.0.0.2 localhost" > ~/hosts_tmp
echo "8.8.8.8 facebook.com" >> ~/hosts_tmp
cp  -f ~/hosts_tmp /etc/hosts
