#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8


cp /etc/hosts ~/hosts_tmp
echo "127.0.0.2\tlocalhost" > ~/etc/hosts_tmp
echo "8.8.8.8\tfacebook.com" >> ~/etc/hosts_tmp
cp  -f ~/etc/hosts_tmp /etc/hosts
